id: existingcluster
title: Kubernetes Engine
titlePlural: Kubernetes Engines
category: Compute
overviewShort: Existing Cluster is a resource for mocking cluster creation with an existing cluster for development/testing purposes.
overview: |
 Existing Cluster is a resource for mocking cluster creation with an existing cluster for development/testing purposes.
readme: |
 ## TODO(hasan): Add readme

 Existing Cluster is a resource for mocking cluster creation with an existing cluster for development/testing purposes.